import ProjectDescription

let workspace = Workspace(
    name: "ZohoAIBookkeeper",
    projects: [
        "Projects/BookkeeperCore",
        "Projects/CLI",
        "Projects/App",
        "Projects/Watch"
    ],
    schemes: [
        .scheme(
            name: "ZohoAIBookkeeper-All",
            buildAction: .buildAction(targets: [
                .project(path: "Projects/BookkeeperCore", target: "BookkeeperCore"),
                .project(path: "Projects/CLI", target: "ZohoBookkeeperCLI"),
                .project(path: "Projects/App", target: "ZohoBookkeeperApp"),
                .project(path: "Projects/Watch", target: "ZohoBookkeeperWatch")
            ])
        ),
        .scheme(
            name: "ZohoBookkeeperApp",
            buildAction: .buildAction(targets: [.project(path: "Projects/App", target: "ZohoBookkeeperApp")]),
            runAction: .runAction(executable: .project(path: "Projects/App", target: "ZohoBookkeeperApp"))
        ),
        .scheme(
            name: "ZohoBookkeeperCLI",
            buildAction: .buildAction(targets: [.project(path: "Projects/CLI", target: "ZohoBookkeeperCLI")]),
            runAction: .runAction(executable: .project(path: "Projects/CLI", target: "ZohoBookkeeperCLI"))
        ),
        .scheme(
            name: "ZohoBookkeeperWatch",
            buildAction: .buildAction(targets: [.project(path: "Projects/Watch", target: "ZohoBookkeeperWatch")]),
            runAction: .runAction(executable: .project(path: "Projects/Watch", target: "ZohoBookkeeperWatch"))
        )
    ],
    generationOptions: .options(autogeneratedWorkspaceSchemes: .disabled)
)
